### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by thisispete** [demian85/gnip#46]
When I have a stream open and I remove all the rules I start getting tons of parse errors in the console: 
`Error: Error parsing JSON: Cannot set property 'tweet' of undefined.`
followed by the tweet object json and then:
``` 
    at Parser.receive (/Users/[directory_redacted]/node_modules/gnip/lib/JSONParser.js:30:28)
    at Gunzip.<anonymous> (/Users/[directory_redacted]/node_modules/gnip/lib/index.js:109:17)
    at Gunzip.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Gunzip.Readable.push (_stream_readable.js:224:10)
    at Gunzip.Transform.push (_stream_transform.js:150:32)
    at Zlib.processCallback (zlib.js:525:10)```

**Comment by thisispete** [comment]
I think this was just a misleading error stack trace, I tracked down through the debugger and error was deeper inside an event listener on 'tweet' inside my project code.. ultimate cause is that the stream continues to deliver matches after the rule is removed.. checking for that condition seems to guard against this error being thrown.
