### ISSUE TITLE
Socket hangs up while writing large number of rules

### ISSUE THREAD

**Issue by jonathankeebler** [demian85/gnip#5]
I'm getting this when I try to write over 2K rules:

  Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at CleartextStream.socketCloseListener (http.js:1526:23)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:693:10
    at process._tickCallback (node.js:419:13)

**Comment by dirkbonhomme** [comment]
Fixed and pushed to master. Thanks for the report!
